# Introduction to TensorFlow

## Coding tutorials
#### [1. Hello TensorFlow!](#coding_tutorial_1)

---
<a id='coding_tutorial_1'></a>
## Hello TensorFlow!

In [1]:
# Import TensorFlow

import tensorflow as tf

In [2]:
# Check its version

tf.__version__

'2.8.0'

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.21.6'

In [ ]:
!python --version

Python 3.7.13


## Check here for further info

[Te damos la bienvenida a Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb)

[TensorFlow versions in Colab](https://colab.research.google.com/notebooks/tensorflow_version.ipynb#scrollTo=nPDc8yQtVxk4)

Let's see some examples before

In [8]:
import numpy as np

# Load a data set
print('Loading data...\n')
data = np.loadtxt('drive/MyDrive/Coursera/GettingStartedTensorFlow2/mnist.csv', delimiter=',')
print('MNIST dataset loaded.\n')

Loading data...

MNIST dataset loaded.



In [9]:
data

array([[2., 0., 0., ..., 0., 0., 0.],
       [9., 0., 0., ..., 0., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.],
       ...,
       [8., 0., 0., ..., 0., 1., 0.],
       [8., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [12]:
data.shape

(70000, 785)

In [13]:
data[:, 1:]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 3., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
data[:, 0]

array([2., 9., 6., ..., 8., 8., 1.])

In [ ]:
# Train a feedforward neural network for image classification

import numpy as np

# Load a data set
print('Loading data...\n')
data = np.loadtxt('drive/MyDrive/Coursera/GettingStartedTensorFlow2/mnist.csv', delimiter=',')
print('MNIST dataset loaded.\n')

# Declare a model
x_train = data[:, 1:]
y_train = data[:, 0]
x_train = x_train/255.

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(16, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])


# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
print('Training model...\n')
model.fit(x_train, y_train, epochs=3, batch_size=32)

print('Model trained successfully!')

Loading data...

MNIST dataset loaded.

Training model...

Epoch 1/3
2188/2188 [==============================] - 4s 2ms/step - loss: 0.5876 - accuracy: 0.7965
Epoch 2/3
2188/2188 [==============================] - 4s 2ms/step - loss: 0.4417 - accuracy: 0.8464
Epoch 3/3
2188/2188 [==============================] - 4s 2ms/step - loss: 0.4104 - accuracy: 0.8568
Model trained successfully!


In [ ]:
data.shape

(70000, 785)

In [ ]:
print(data)

[[2. 0. 0. ... 0. 0. 0.]
 [9. 0. 0. ... 0. 0. 0.]
 [6. 0. 0. ... 0. 0. 0.]
 ...
 [8. 0. 0. ... 0. 1. 0.]
 [8. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
data[0][0]

2.0

In [ ]:
len(data[0])

785

In [ ]:
data[0]

array([  2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   4.,   0.,   0.,   0.,   0.,   0.,  62.,  61.,  21.,  29.,
        23.,  51., 136.,  61.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  88.,
       201., 228., 225., 255., 115.,  62., 137., 255., 235., 222., 255.,
       135.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,  47., 252., 234., 238., 22

#### Importance of 
Ctrl+M and then B

Ctrl+M and then M

Ctrl+M and then Y


### How to connect you Google Drive with your Google Colab Notebook

In [ ]:
from google.colab import drive
drive.mount('drive')

In [ ]:
file = open("drive/MyDrive/Coursera/GettingStartedTensorFlow2/test.txt")
print(file.read())

Hello there!


### How to call bash commands in a Notebook

In [ ]:
# Prepend the command with an exclamation mark
!ls

drive  gdrive  sample_data


In [ ]:
! ls drive/MyDrive/

 100DaysOfCode		      eDx
 BlueTab		     'Introducción a Machine Learning con Python'
'Colab Notebooks'	      Refs.gsheet
 Coursera		      Telefónica
 Cursus			      TensorFlow_Keras
'Documento sin título.gdoc'
